(ns advent-of-code-2018.day-two
  (:require [clojure.math.combinatorics :as combo]))

(def easy-input
  ["abcdef" "bababc" "abbcde" "abcccd" "aabcdd" "abcdee" "ababab"])

(def part-two-easy
  ["abcde"
   "fghij"
   "klmno"
   "pqrst"
   "fguij"
   "axcye"
   "wvxyz"])

(def input
  ["cvfueihajytpmrdkgsxfqplbxn"
   "cbzueihajytnmrdkgtxfqplbwn"
   "cvzucihajytomrdkgstfqplqwn"
   "cvzueilajytomrdkgsxfqwnbwn"
   "cvzueihajytomrdkgsgwqphbwn"
   "wuzuerhajytomrdkgsxfqplbwn"
   "cyzueifajybomrdkgsxfqplbwn"
   "cvzueihajxtomrdkgpxfqplmwn"
   "ivzfevhajytomrdkgsxfqplbwn"
   "cvzueihajytomrdlgsxfqphbbn"
   "uvzueihajjtomrdkgsxfqpobwn"
   "cvzupihajytomrdkgsxfqplpwe"
   "cvzueihajyvomrdkgsxfqplbrl"
   "cczueihajytomrdkgsnfqpxbwn"
   "cvzueigajytdmrdkgsxyqplbwn"
   "cvzujihljytomrdkgsxuqplbwn"
   "cvzueisajytomrddgsxkqplbwn"
   "cvzneihajytomrdkgsgaqplbwn"
   "cvzueihajytomrdkgsinmplbwn"
   "cveueihajyromrdkgsxfqplown"
   "cypueihajytotrdkgzxfqplbwn"
   "cvzuoihajytomvdqgsxfqplbwn"
   "cvzuekhejytwmrdkgsxfqplbwn"
   "cvzseihajytomrdkgsxfqgmbwn"
   "cvfuhihajytomrdkgsxfqplbwi"
   "cvzueihujxtomrdkgsufqplbwn"
   "cvzueihdjytomrdogsxfqplbwh"
   "cvzueihdjyfohrdkgsxfqplbwn"
   "cvtudihajytolrdkgsxfqplbwn"
   "cvzueihajytymrdkgshzqplbwn"
   "cvzuebhajytomxdkgsxfqplbwt"
   "cvzulihajyxomrdkgsbfqplbwn"
   "cvzueihajywomrdkgsxfqplbts"
   "cvzueihajytouodkdsxfqplbwn"
   "cvzueihajytomgdkgqxfqklbwn"
   "cvzubihajytomvdkgsxfqplmwn"
   "cvhueihajyyocrdkgsxfqplbwn"
   "zvzueihajytourdkgsxflplbwn"
   "cvzbeihajytomadkgsxfoplbwn"
   "cvzueihajytomrdkgnxfqplbsl"
   "cvfueihajftkmrdkgsxfqplbwn"
   "cvzuexhajytomryugsxfqplbwn"
   "cvzueihajytomsckgsxfqalbwn"
   "cvzuexhajytomrdkbsxfqpluwn"
   "cvzueihajytbmrtkgsxwqplbwn"
   "cvzueihajytomrdigsxfqqlbsn"
   "cvzweihajytomydkgsxfmplbwn"
   "bvzteihajytimrdkgsxfqplbwn"
   "cvzueihajytpmrdkgsxfcpbbwn"
   "cvzueigsjltomrdkgsxfqplbwn"
   "cvzueihajytomrikgsxfopldwn"
   "cvzueihajstomrdkgsxfqplgon"
   "cvzueimajytomrnkxsxfqplbwn"
   "cvzleihagatomrdkgsxfqplbwn"
   "cvbueihajotomrdkgsxfqjlbwn"
   "cvzueihajytomrdkgsxfqppnvn"
   "hvzueihajytomrdkghxfkplbwn"
   "cvzueigajytxmrdkgsxfqplbjn"
   "cvzueihaaxtokrdkgsxfqplbwn"
   "cvzueihajyeomrdkgujfqplbwn"
   "cvzueiwajpoomrdkgsxfqplbwn"
   "cvzieidtjytomrdkgsxfqplbwn"
   "cvzueihalytomrakbsxfqplbwn"
   "wtzueihajytomrdkgsxfqplbwq"
   "cvzuelhaiytomrdkgsxfqplcwn"
   "cvzueihajytomrdkgsxfqslswd"
   "cvzueihajytomrykgssfqplbon"
   "cvzueihfjytovrdegsxfqplbwn"
   "cvzueihajytomldqgsxfqplbwy"
   "cvzleihjjytomrtkgsxfqplbwn"
   "cvzueihaldtomrdtgsxfqplbwn"
   "cvzueihajytzmrdkgsxfeplqwn"
   "cvzueihrjytomddkgsxfqpgbwn"
   "cyzulihajytokrdkgsxfqplbwn"
   "cvsueihajytoordfgsxfqplbwn"
   "fvzueyhajytomrdkgaxfqplbwn"
   "cczueihajytobrdkgsefqplbwn"
   "cvzueihajytomcdrgscfqplbwn"
   "cvzuexhajyvomrdkgssfqplbwn"
   "cvzsmihajyiomrdkgsxfqplbwn"
   "cvzzeihajttomrdkgsxzqplbwn"
   "cvzseihajytomrdkgsxfqpebvn"
   "cvzueihajgthmrdkgsbfqplbwn"
   "ruzueihajytomrdkgsxfqphbwn"
   "cvzueihajytofrdkgsnfrplbwn"
   "cvzuetdajytojrdkgsxfqplbwn"
   "fvzueihajytomrdkghxfqpobwn"
   "cvzueihsjytomrdkgsxfqglbxn"
   "cvzueihajytowrdkgsxfqpsbun"
   "cvzteihaiytomrdkfsxfqplbwn"
   "cvzueihajytkmrdkrsxfqplvwn"
   "cvzueihajyoomrdkasxfqjlbwn"
   "lvzurihajytkmrdkgsxfqplbwn"
   "cvzueihajyyomrdagsxfqelbwn"
   "cvfueihajytomrdkgsxfqplbbx"
   "cvwueihajytommdkgkxfqplbwn"
   "cvzucicajytomrdkgsxcqplbwn"
   "dvzueihahytgmrdkgsxfqplbwn"
   "cvzuechajytomrdkgsxfqelwwn"
   "cvzuekhajytomrdkgsxknplbwn"
   "cvtueihajytomphkgsxfqplbwn"
   "cvzueihabytnzrdkgsxfqplbwn"
   "cvzusihajytomrdkgfxfqplban"
   "cvfueihajytomcdfgsxfqplbwn"
   "mvzueihapytomrdkgsxfdplbwn"
   "cvzueihajytomhdkgsxmqppbwn"
   "jvsueihajytomrdkgsxfqplbln"
   "cvzujihajybomrdkgsxtqplbwn"
   "cvzuekhawytomrdkgsxfqplbwc"
   "svzueihanytomrdogsxfqplbwn"
   "cvzujihajytodrdkgslfqplbwn"
   "cvgdeihajytorrdkgsxfqplbwn"
   "cvzbeihajytoprdkgsxfqplbyn"
   "cvzueihkyytomjdkgsxfqplbwn"
   "cvzuelhojytomrdkgsxfqjlbwn"
   "evzueihajytimrdkgsxfqpsbwn"
   "cvzueihajydomrdkjsxfqplbjn"
   "ovzteihajytosrdkgsxfqplbwn"
   "cvzueihajyaomrdzgsxfqplbgn"
   "cvzuewhajmtomrdkgsufqplbwn"
   "cvzueihajqtomhukgsxfqplbwn"
   "cvzueihajytomzqkgsxfqplbwk"
   "cazuewhakytomrdkgsxfqplbwn"
   "clzueihatytomrdkgzxfqplbwn"
   "dvzueihajytomqdkgsxfqpnbwn"
   "cvzueidajdtomrdkgsxtqplbwn"
   "cvzueihabytowrdkgsxoqplbwn"
   "cvzujihwjytomrdkgsxeqplbwn"
   "cvtuedhajytomrdkgsxfqplbbn"
   "cvzueihajcgomrdkgsxfqplswn"
   "cvzuephajyiomrdngsxfqplbwn"
   "cvzueihajythmqdkgsxfqplbwf"
   "cvzueitajytomrdkgsxfepvbwn"
   "cvzueihajytomydkgsxfqplvwb"
   "dvzueshajytomrddgsxfqplbwn"
   "cvzueihajytomrdkgvxfqpwben"
   "cvzueihajytomrdkgvxfpplwwn"
   "cvzuefhajftomrdkgsxfqrlbwn"
   "cvzueihajytpmrvkgsxfqplbcn"
   "cvzueihajytohrdkgsxfqxnbwn"
   "cvzueihajytomrdposxfqulbwn"
   "cozueihajytomrpkgsxfqrlbwn"
   "cvzuuihaxytomrdkgsxfqplbtn"
   "cvzueihajytomrbzgsxyqplbwn"
   "cveueihajyxoqrdkgsxfqplbwn"
   "cvzueihajytomrkkgsxfqptbrn"
   "cvzuezhajatomrdkssxfqplbwn"
   "cpzueihajytomrdkgsxfhplbwo"
   "lviueihajytomrekgsxfqplbwn"
   "cvzueihwjytomrdkusxfyplbwn"
   "cvzgeihajytomwdkgsxfrplbwn"
   "cvzsejhzjytomrdkgsxfqplbwn"
   "cvzuuihajytomrdkgsxfqdlbwz"
   "cvzjeihajytomrdugsxftplbwn"
   "cvzueihaxytomrrkgsxfmplbwn"
   "cvzueihajgtomrdhgsxfqplwwn"
   "cvzulihajytomedkgsxfqplewn"
   "cvzueivajytomrdkmsxfqplbwc"
   "cvzuervajytomrdkgsxfwplbwn"
   "cvzuemhcjytomrdkgslfqplbwn"
   "cvzyerhauytomrdkgsxfqplbwn"
   "cvzueihaoytomrdkgsyfqplewn"
   "cvzueihanytomrdkgsafkplbwn"
   "cvzueihajvtomrdugsxfqpcbwn"
   "chzueihajytamrdxgsxfqplbwn"
   "cvzueihalytomrdsgsxfqplbln"
   "cvzueihajytoyaykgsxfqplbwn"
   "tlzueihajyeomrdkgsxfqplbwn"
   "cvpueihajytbmrdkgsxfxplbwn"
   "cvzueihajytomjdkgsxuqplkwn"
   "cvzueihajygomrdkgkxfqplbwg"
   "cvzueihajhtomrdkgbxsqplbwn"
   "cvzurihajytomrdkgsafqplbwx"
   "cdzuezhajytomrdkgsxrqplbwn"
   "cvbueihajytotrwkgsxfqplbwn"
   "cwzkeihajytomrdkgsxfqplbwh"
   "cvzheihajytolrikgsxfqplbwn"
   "cozuevhajytomrdkgkxfqplbwn"
   "chzueihajytomrjkgsxfqulbwn"
   "cvzueihkjyromrdkgsxvqplbwn"
   "cvzveihajytomrdkgsxpqplnwn"
   "cvzueihajytoirdkgsxfqihbwn"
   "cvoueihajytomrdkgsxfqpdawn"
   "pvzueihajytomrdkgnxfqplbfn"
   "cvzueihakytomxdkgssfqplbwn"
   "cvzueivajytomrdbgsxaqplbwn"
   "cvzueihajytokrdkgszrqplbwn"
   "cvzuevhajytomrdkgsxgqplbwi"
   "cvzueihajylomrdkgsxflplbpn"
   "hvzueihajytomvdkgsxfqplgwn"
   "cvzleihajytymrrkgsxfqplbwn"
   "crzueieajytomrdkgsxfqplbon"
   "cszueihajytomrdlgqxfqplbwn"
   "cvzueihacytomrdkgsxfjblbwn"
   "cvzreihajytomrdkgsxfqplzun"
   "cvzurihajytomrdkgsxiqplawn"
   "uvzueihajyhovrdkgsxfqplbwn"
   "cvzueihajyqodrdkgssfqplbwn"
   "cvzwiihrjytomrdkgsxfqplbwn"
   "cqzueihajytomrdkgjxfqplban"
   "cvmueihajytoordkgsxfqplbyn"
   "cypueihajytomrdkgzxfqplbwn"
   "cvzueihajykomrdkgsmfqplbtn"
   "cvzueidajytimrdkgsxfqpdbwn"
   "cvzheihajytomrdkgsxfqpfewn"
   "dvzueihajytumrdzgsxfqplbwn"
   "cvzueixajytomrdkgsvfqplgwn"
   "cvzuevhzjyzomrdkgsxfqplbwn"
   "cvyeeihajytomrdkgsxnqplbwn"
   "cvzueihajytomrdkggtpqplbwn"
   "cvzceiyajytomrdkgexfqplbwn"
   "cvzuelhajyyomrdkzsxfqplbwn"
   "cvzhzihajygomrdkgsxfqplbwn"
   "cvzueihwjytomrdkgsgfqplbrn"
   "cvzsevhajytomrdkgqxfqplbwn"
   "cvzueiuajytomrdkgsxfppebwn"
   "nvzueihajytemrdkgsxwqplbwn"
   "cvzueihajytocgdkgsxfqvlbwn"
   "cczusihajytomrdkgsxfqplbpn"
   "cmzueihajytomrdkbsxwqplbwn"
   "cvzumfdajytomrdkgsxfqplbwn"
   "cvzueihcjytomrdkgsxfqplbkl"
   "cvzueihajytomawknsxfqplbwn"
   "kvzueihijytomrdkgsxdqplbwn"
   "cdzutihajytomrdkgsxfkplbwn"
   "cvzufihadylomrdkgsxfqplbwn"
   "cvzueihajytomrgkxsxfqphbwn"
   "cvzuewhajyzomrdkgsxfqelbwn"
   "cvzueihajytomrdkgqxfqelbwc"
   "cvzueshajyoomrdkgsxfqflbwn"
   "cvzueihajyromrekgixfqplbwn"
   "chzugihajytomrdkgsxfqplawn"
   "cvzueihajytomrdkgsxfhpmbwy"
   "cvzueihacytodxdkgsxfqplbwn"
   "cvzurihajytourdkgsdfqplbwn"
   "cvzzeihmjytomrddgsxfqplbwn"
   "cvzucyhajygomrdkgsxfqplbwn"
   "ckzueihzjytomrdkgsxwqplbwn"
   "cvlueihajmtozrdkgsxfqplbwn"
   "cvzkeihajytomrdkgsxfqclbwc"
   "cvzueihajytomrdkgsxgdplbwa"
   "cvzueihyjytoxrdkgcxfqplbwn"
   "cvzueizavytomfdkgsxfqplbwn"
   "cvzueihajwtosrdkgsxfqllbwn"
   "cvzueihajytomrdaksxfqpllwn"
   "cvzuuihojytombdkgsxfqplbwn"
   "cvzuiibajytpmrdkgsxfqplbwn"
   "cvzueihajyuomydkgsxfqplzwn"
   "cvzueihajytimrmkgsxfqplfwn"
   "cvzueihajytomrdkgzxfqpljwo"])

(defn find-frequencies
  [string]
  (let [char-counts (frequencies (seq string))
        values (vals char-counts)
        three-match (if (some #(= 3 %) (seq values)) 1 0)
        two-match (if (some #(= 2 %) (seq values)) 1 0)]
    [two-match three-match]))

(defn checksum
  [input]
  (let [frequencies (map find-frequencies input)
        twos (reduce + (map #(nth % 0) frequencies))
        threes (reduce + (map #(nth % 1) frequencies))]
    (* twos threes)))

(defn match?
  [a b]
  (if (= a b) 0 1))

(defn distance
  [input]
  (let [a (nth input 0)
        b (nth input 1)]
    (map match? (seq a) (seq b))))

(defn distance-to-combination
  [combination]
  (let [distance (distance combination)]
    {:combination combination :distance distance :dist-val (reduce + distance)}))

(defn find-matching-boxes
  [input]
  (let [combinations (vec (map vec (combo/combinations input 2)))]
    (filter #(= 1 (:dist-val %)) (map distance-to-combination combinations))))

(defn similar-chars
  [{:keys [combination distance]}]
  (let [string (nth combination 0)]
    (reduce str (map #(nth % 0)
               (filter #(= (nth % 1) 0)
                       (map (fn [a b] [a b]) (seq string) distance))))))

